lib/islands_vue_client_web/router.ex
defmodule Islands.Vue.ClientWeb.Router do
  use Islands.Vue.ClientWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Islands.Vue.ClientWeb do
    pipe_through :browser

    get "/", GameController, :index
    get "/games", GameController, :index
    get "/games/new", GameController, :new
    get "/games/:id", GameController, :join
    # resources "/games", GameController, only: [:new, :create, :show]

    get "/sessions/new", SessionController, :new
    post "/sessions", SessionController, :create
    # resources "/sessions", SessionController, only: [:new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Islands.Vue.ClientWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: Islands.Vue.ClientWeb.Telemetry
    end
  end
end

lib/islands_vue_client_web/controllers/session_controller.ex
defmodule Islands.Vue.ClientWeb.SessionController do
  use Islands.Vue.ClientWeb, :controller

  alias Islands.Vue.Client.Player
  alias Plug.Conn

  @spec new(Conn.t(), map) :: Conn.t()
  def new(conn, _params) do
    render(conn, "new.html")
  end

  @spec create(Conn.t(), map) :: Conn.t()
  def create(conn, %{"player" => %{"name" => name, "gender" => gender}}) do
    player = Player.new(name, String.to_atom(gender))

    conn
    |> put_session(:player, player)
    |> redirect_back_or_to_new_game
  end

  ## Private functions

  @spec redirect_back_or_to_new_game(Conn.t()) :: Conn.t()
  defp redirect_back_or_to_new_game(conn) do
    # The 'return_to' path retrieved by 'get_session' will be nil if going
    # to '/sessions/new' directly instead of the usual '/' or '/games/new'.
    path = get_session(conn, :return_to) || Routes.game_path(conn, :new)

    conn
    |> delete_session(:return_to)
    |> redirect(to: path)
  end
end

lib/islands_vue_client_web/views/session_view.ex
defmodule Islands.Vue.ClientWeb.SessionView do
  use Islands.Vue.ClientWeb, :view

  @spec path(Plug.Conn.t(), Path.t()) :: Phoenix.HTML.safe()
  def path(conn, image_path) do
    Routes.static_path(conn, image_path)
  end
end

lib/islands_vue_client_web/templates/session/new.html.eex
<div class="row">
  <div class="col-xs-8 col-xs-offset-2 text-center">
    <h1>Welcome!</h1>
    <h4>First up, we need your name and gender:</h4>
    <%= form_for @conn, Routes.session_path(@conn, :create), [as: :player],
                 fn f -> %>
      <div class="form-group">
        <%= text_input f, :name, placeholder: "Name",
                          autofocus: true, required: true %>
        <div class="form-group">
          <label class="radio-inline">
            <%= radio_button f, :gender, "m", checked: true %>
            <img src="<%= path(@conn, "/images/male-sign.png") %>"
                 alt="Male" width="30">
          </label>
          <label class="radio-inline">
            <%= radio_button f, :gender, "f" %>
            <img src="<%= path(@conn, "/images/female-sign.png") %>"
                 alt="Female" width="30">
          </label>
        </div>
      </div>
      <%= submit "Play Islands!", class: "btn btn-primary game-btn" %>
    <% end %>
  </div>
</div>